version: "2"
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - 9160
      - 9042
      - 7199
      - 7001
    environment:
      - CASSANDRA_START_RPC=true

    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge