version: "2"
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - ./data/cassandra:/var/lib/cassandra
